version: '3'

services:
  mysql-docker-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
    volumes:
      - /data/mysql
    ports:
      - 3306:3306
  spring-boot-myapp:
    image: spring-boot-myapp-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    environment:
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: test123
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/spring_app_db

    volumes:
      - /data/spring-boot-app
